name: commands workflow

on: 
  push:
    branches: 
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo "::debug::Test debug message"
      - name: error
        run: echo "::error file=/Readme.md,line=2,endColumn=5::Test error message"
      - name: masking
        id: masking
        run: |
          var=12345
          echo "::add-mask::$var"
          touch test.txt
          echo $var >> test.txt
          echo "KEY=$var" >> $GITHUB_OUTPUT
      - name: print masking
        run: |
          cat test.txt
          echo $KEY
      - name: job summary
        run: |
          echo "# *Summary*" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- point 1" >> $GITHUB_STEP_SUMMARY
          echo "- point 2" >> $GITHUB_STEP_SUMMARY
