name: manual-wf

on:
  workflow_dispatch:
    inputs:
      name:
        description: user name
        required: true
        type: string
      role:
        description: user role
        required: true
        type: choice
        default: user
        options:
          - user
          - admin
      passphrase:
        description: passphrase
        required: false
        type: string

jobs:
  manual-flow:
    runs-on: ubuntu-latest
    steps:
      - name: create pass
        run: |
          echo ${{ inputs.passphrase || 'Nemo' }} | base64 > ./pass_base64.txt
      - name: create greeting
        run: |
          echo "Hello, ${{ inputs.name }}. You authorized as ${{ inputs.role }}. You pass to login: $(cat ./pass_base64.txt)"
