name: needs workflow

on: push

jobs: 
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps: 
            - name: step 1
              run: |
                echo job2 step1 before error
                echo "::error title=Job2 error title::Job2 error message"
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo job1 step1
    job3:
        runs-on: ubuntu-latest
        needs: [job1, job2]
        steps:
            - name: step1
              run: echo job3 step1
    job4:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: [job1, job2]
        steps:
            - name: step1
              run: echo job4 step1