name: scheduled workflow

on:
  schedule:
    - cron: '*/5 * * * ?'

jobs:
  main:
    name: echo date
    runs-on: ubuntu-latest
    steps:
      - name: echo date
        run: echo 'current date is $(date)'