name: webhook workflow

on: 
  repository_dispatch:

jobs: 
    main:
        name: main job
        runs-on: ubuntu-latest
        steps:
            - name: print payload
              run: |
                  echo ${{ toJSON(github.event.client_payload.data) }}
