name: webhook workflow

on: 
    repository_dispatch: 
        types: [custom_event]

jobs: 
    main:
        name: main job
        runs-on: ubuntu-latest
        steps:
            - name: print payload
              run: |
                  echo ${{ toJson(github.event.client_payload.data) }}
