name: workflow with docker action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    environment: development
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: nik-webdevelop/docker-action@v1.0.3
        with:
          name: 'foo bar'
      - name: Get the output time
        run: echo ${{ steps.hello.outputs.message }}
